backend:
  name: git-gateway
  branch: master

media_folder: "images"
public_folder: "images"
site_url: https://wwww.itsamatterofflow.com
display_url: https://wwww.itsamatterofflow.com
logo_url: https://wwww.itsamatterofflow.com/images/1024x1024.png
publish_mode: editorial_workflow

collections: 
  - name: "projects"
    label: "Projects"
    folder: "projects"
    
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
