 backend:
   name: git-gateway
   branch: master

media_folder: "site/images/"
public_folder: "/images"
site_url: https://itsamatterofflow.com
public_url: https://itsamatterofflow.com

collections: 
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
